language: go
go:
  - "1.10"
  - "1.11"

install: make install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: make test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
